### ISSUE TITLE
"Invalid API key" response

### ISSUE THREAD

**Issue by Threesixty** [Ayctor/CityScan#2]
Hi there,

When tried to activate an address with your extension the Cityscan WS says "Invalid API key". Tested with CityScan live and same Api key and it works.

![Screenshot_2019-10-25 Exception](https://user-images.githubusercontent.com/6042147/67578067-fd881680-f741-11e9-98e7-6f8cf64100a0.png)

![image001](https://user-images.githubusercontent.com/6042147/67578076-02e56100-f742-11e9-989e-1d5dd58fc3e7.png)

Thank you for your feedback.

Michael

**Comment by ErwanGuillon** [comment]
Hey Michael,

In your PHP file, the CityScan class is created for `preprod` and in your Postman screenshot it's prod.

Try replacing `preprod` for `prod` in your PHP code.

The documentation is not clear about this parameter and we will correct it soon.

Have a nice day.

**Comment by Threesixty** [comment]
Great Erwan, it works now. Yesterday we tried both `prod` and `preprod` and it didn't work. 
We informed CityScan and then I guess they updated something for us between yesterday & now.

Thank you for your quick response.

**Comment by Threesixty** [comment]
Hello Erwan,

Added a function to reactivate existing addresses by ids/extIds:

    /**
     * Reactivate an address
     *
     * @param array $arrayIds List of Address Ids
     * @param bool $isExternal Define if the addresse id is external or not
     * @return \StdClass
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function reactivateAddress($arrayIds, $isExternal = false)
    {
        if ($isExternal) {
            $params = [
                'extAddressIds' => $arrayIds,
            ];
        } else {
            $params = [
                'addressIds' => $arrayIds,
            ];
        }

        return $this->request('POST', 'addresses/reactivate', $params);
    }

**Comment by ErwanGuillon** [comment]
@Threesixty Can you make a PR so we can merge it to master?

Thanks
